### ISSUE TITLE
Comet chat  SDK 2.1.6 crashing IOS application while initiating call 

### ISSUE THREAD

**Issue by SheheryarShahVozye** [cometchat-pro/ios-swift-chat-app#20] opened 2021-02-01 10:02 UTC
First of all, I'm not using comet-chat UI Kit, instead, I'm using comet-chat SDK with my own swift ui....  all the feature works fine but sometimes i experience error on comet chat method named initiate call which crashes the whole application. further there is no try catch in code where we can track such errors. please look into it as its very crucial for the sustainability of my application. the error I receive is Thread 25: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0).

**Comment by jeetkapadia** [comment] 2021-02-01 10:12
Hi @SheheryarShahVozye,

I have checked the same in iOS Swift Sample App having version **2.1.6-beta2** and it is working as expected. I suggest you please use the **2.1.6-beta2** version of SDK in your App. This should solve the issue faced on your end. Here is the link to our iOS Swift Chat app:

https://github.com/cometchat-pro/ios-swift-chat-app

You can refer to the code for the implementation of calling functionality in your App. In case if you are still facing the issue then provide us the complete log so that we can have a look into it.

Regards

**Comment by SheheryarShahVozye** [comment] 2021-02-01 11:19
No issue right now but it happens once or twice a week very often. just to clarify we have implemented the same functionality as suggested in sample app

**Comment by jeetkapadia** [comment] 2021-02-01 11:30
Okay, Incase if you face the issue again then please share the complete crash logs with us so that I and my team can have a better understanding of the issue faced by you. I am closing this thread for now. Feel free to open it again in case if you face a crash.

**Closed by jeetkapadia** 2021-02-01 11:30 UTC

**Comment by paarthsabharwal** [comment] 2021-02-01 12:12
Hi @SheheryarShahVozye ,
If the issue is persistent, please feel free to email us at help@cometchat.com for prompt technical support.
Please feel free to reach out if you need any CometChat assistance.
